import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <div className="mx-auto px-2 max-w-2xl md:px-4 py-6 md:py-10 lg:max-w-7xl lg:px-8 h-full p-0">
        <div className="grid grid-cols-12">
          <div className="col-span-3 hidden md:block">
            <div className=" border-1 border-gray-300">
              <div className="border-b-1 border-gray-300 bg-gray-100 flex flex-col gap-1 items-center justify-center py-3">
                <div className="w-7 h-7 p-12 rounded-full bg-black text-5xl  text-white flex justify-center items-center">
                  S
                </div>
                <p className="text-lg font-medium">SBS</p>
                <span className="text-base text-gray-400 "> #BeIncane</span>
              </div>
              <div className="flex flex-col">
                <Link href="orders" className="p-4 text-sm cursor-pointer">
                  Order
                </Link>
                <hr />
                <Link href="address" className="p-4 text-sm cursor-pointer">
                  Address
                </Link>
                <hr />
                <Link href="profile" className="p-4 text-sm cursor-pointer">
                  Profile
                </Link>
                <hr />
                <Link href="favourites" className="p-4 text-sm cursor-pointer">
                  Favourites
                </Link>
                <hr />
                <Link href="coupons" className="p-4 text-sm cursor-pointer">
                  Coupons
                </Link>
                <hr />
                <Link href="tickets" className="p-4 text-sm cursor-pointer">
                  Tickets
                </Link>
                <hr />
                <button className="bg-yellow-300 flex items-center justify-center py-1.5 m-3 rounded-lg hover:bg-yellow-200 font-medium">
                  LOGOUT
                </button>
              </div>
            </div>
          </div>
          <div className="col-span-12 md:col-span-9 pl-0 md:pl-32">
            {children}
          </div>
        </div>
      </div>
    </>
  );
}
